### ISSUE TITLE
Compactor is getting stuck when shift-click items in

### ISSUE THREAD

**Issue by utoc** [bdew/compacter#3]
This is an inconsistent issue and I only get it about 1 in 4 times.  I'm running 1.0.0.10 with FML 1448. The issue occurs when shift-clicking items in like cobble, gravel or other 3x3 grid compacted items and it has to be 4-6+ stacks in order for the symptoms to present.  Here is what happened after shift+clicking (not space+click, I am only sending one stack at a time):

http://i.imgur.com/0eVyCkN.png

It's stuck at that point.  To determine if the client was descyned, I reconnected and found the cobble queue higher:

http://i.imgur.com/JetnLha.png

Full mod list here: https://www.reddit.com/r/BBQSauce/wiki/modlist

**Comment by bdew** [comment]
That's odd, and i can't reproduce it. 

Please try adding additional items after it's stuck with:
- Manually moving a stack from your inventory
- Shift clicking a stack
- Using some kind of automation (hopper, pipes, etc)

Does any of those make it work again?

**Comment by utoc** [comment]
I actually found some consistency in the issue.  Any items that are inserted into the compactor's inventory when it doesn't have enough power are somehow forgotten until they're reinserted.  You can duplicate this yourself by having a creative cell and two compactors.  One compactor can be connected with a cryo-stabilized flux-duct or any unlimited rf/t duct of your chooseing.  The other should have something like a cheap redstone conduit (Using Thermal Dynamics for my example here)

If you put a ton of cobble/dirt/gravel into a diamond chest and use the fastest pipes you have to insert it into the compactor, the one with the lesser, 200rf/t transfer rate will undoubtably get stuck.

As for your questions:
- Shift clicking an item stack does not help the situation any
- Manually clicking the stack to remove it from the inventory and then replacing it does not help, all offending items must be removed before it gets unstuck.
- Automation changes nothing.

This is the setup I'm using that makes it fail consistently.  https://i.imgur.com/iC4akQf.png

**Comment by bdew** [comment]
Hm i think i know what's going on.

The compacter will not process an item if it doesn't have energy to process ALL items of that type at once. Moreover if it sees it's out of power, it will enter a mode that suspends processing until it gets more. This is for performance reasons. 

Your configs significantly increase operation cost (1k RF per operation) while not adding a large enough power buffer (only 16k RF).

So when you have more than 16x9 of cobble - it becomes impossible to process and gets stuck.

I'd recommend changing either value so that the buffer is at least 450x activation cost - this allows it to process a full inventory of 2x2 craftable items + some extra for the invisible queue used for recursive mode.

**Comment by utoc** [comment]
Ah, we have a bingo!  I changed the buffer to 500,000 just for grins and it didn't get stuck until the buffer limit was hit.  I will pass this on to my users that this is intended performance functionality of the compactor.  Thanks for explaining it bdew!

**Comment by bdew** [comment]
I'd still recommend setting it to sensible values and not just "passing it on to the users" :P

**Comment by utoc** [comment]
Thats the plan, I'll change the config to 500K in the next release but the users still need to know that if they use Steve's Factory Manager or something else wickedly fast that the Compactor could still get stuck

**Comment by bdew** [comment]
It won't get stuck with correct settings.

Worst case - if you don't have enough power it will wait until the buffer fills up then proceed working.

If the power is adequate it can process [anything you throw at it](https://www.youtube.com/watch?v=lNdfV0pA3Iw) - try it with the testing block right next to a compacter - it will fully fill it's inventory with cobble every tick (nothing can be faster than that)

The only reason it was getting stuck is that it was waiting for more power than it could hold due to config settings.
